const samplePayload = {
  source: "apify",
  status: "success",
  username: "demo.lima",
  generated_at: "2026-04-10T10:30:00.000Z",
  metadata: {
    username: "demo.lima",
    full_name: "demo Lima",
    biography: "",
    followers: 0,
    followees: 0,
    is_verified: false,
    posts_count: 12,
    source: "apify",
  },
  metrics: {
    followers: 0,
    following: 0,
    ratio: 0,
    post_frequency: 0.55,
    avg_engagement: 466.17,
    captions_count: 12,
    top_hashtags: [{ hashtag: "vamoscontodo", count: 2 }],
  },
  analysis: {
    total_posts_analyzed: 3,
    total_likes: 5395,
    total_comments: 199,
    avg_likes: 449.58,
    avg_comments: 16.58,
    top_hashtags: [
      { value: "gastronumus", count: 1 },
      { value: "gastroart", count: 1 },
    ],
    top_mentions: [
      { value: "juan_luismt_", count: 4 },
      { value: "demo.mas.lima", count: 2 },
    ],
    best_post_by_likes: {
      id: "a1",
      likes_count: 1434,
      comments_count: 50,
      hashtags: ["gastronumus", "gastroart"],
      mentions: ["demo.lima"],
      timestamp: "2026-04-09T16:53:47.000Z",
    },
    best_post_by_comments: {
      id: "a1",
      likes_count: 1434,
      comments_count: 50,
      hashtags: ["gastronumus", "gastroart"],
      mentions: ["demo.lima"],
      timestamp: "2026-04-09T16:53:47.000Z",
    },
    posts: [
      {
        id: "a1",
        caption: "Post 1",
        likes_count: 1434,
        comments_count: 50,
        hashtags: ["gastronumus", "gastroart"],
        mentions: ["demo.lima", "juan_luismt_"],
        owner_username: "demo.lima",
        owner_full_name: "demo Lima",
        timestamp: "2026-04-09T16:53:47.000Z",
        url: "https://www.instagram.com/p/a1",
      },
      {
        id: "a2",
        caption: "Post 2",
        likes_count: 520,
        comments_count: 14,
        hashtags: ["chefstalk"],
        mentions: ["juan_luismt_"],
        owner_username: "demo.lima",
        owner_full_name: "demo Lima",
        timestamp: "2026-03-25T10:00:00.000Z",
        url: "https://www.instagram.com/p/a2",
      },
      {
        id: "a3",
        caption: "Post 3",
        likes_count: 180,
        comments_count: 6,
        hashtags: ["vamoscontodo"],
        mentions: ["demo.mas.lima"],
        owner_username: "demo.lima",
        owner_full_name: "demo Lima",
        timestamp: "2026-02-10T12:00:00.000Z",
        url: "https://www.instagram.com/p/a3",
      },
    ],
  },
  posts: [],
  render_hints: {
    seed: "demo.lima:seed",
    node_count: 9,
    energy: 466.17,
    dominant_hashtag: "gastronumus",
    post_density: 0.55,
  },
};

export default samplePayload;
